### PR TITLE
Data #4

### PR DESCRIPTION
**Pull request by sdiby**
@ptatian I've added new ACS tabs to BP program at city, ward, and bridgepark levels.

### CODE REVIEW

**Comment by sdiby** [comment]
@rpitingolo @ptatian 
Rob, this program is also ready for your review.

**Comment by rpitingolo** [comment]
@sdiby I'll review.

**Comment by rpitingolo** [comment]
@sdiby please check where you have GrossRent: in the variable lists. I think you need to change it to include the _&year.

**Comment by sdiby** [comment]
@rpitingolo I fixed GrossRent vars--program is ready for your review.

**Comment by rpitingolo** [comment]
@sdiby thanks. Have you done the final batch submit for the ACS data? I think that needs to happen before I can test these fully.

**Comment by sdiby** [comment]
@rpitingolo sorry about that--thanks for catching that. Final batch submits for dc, md, and va ACS data are now complete.

**Comment by rpitingolo** [comment]
@sdiby it looks like RentCostBurdenDenom_2011_15 and OwnerCostBurdenDenom_2011_15 are missing from all of the ACS summary files. I also think for the city-data we should switch to have it use ACS.acs_2011_15_dc_sum_regcnt_regcnt since that's the actually county-level data, not built up from tracts.

**Comment by sdiby** [comment]
@rpitingolo program runs without errors on my machine. Thanks again for helping with the ACS macro errors. 

If this looks okay, feel free to review and merge.

**Comment by ptatian** [comment]
@rpitingolo It seems like work on this issue is complete? If so, would you please merge the pull request and close issue #4? Thank you.

**Comment by rpitingolo** [comment]
@ptatian I'm double checking this one and will close/merge once confirmed.

**Comment by ptatian** [comment]
@rpitingolo Checking in again on the status of this issue.

**Comment by ptatian** [comment]
@rpitingolo @sdiby Hi folks. This pull request, and associated issue #4, remains open but it seems like the work was completed long ago. Is there any reason why it should not be merged and closed?

**Comment by rpitingolo** [comment]
@ptatian no. I'll merge and close this one.

**Pull request merged**
