### PR TITLE
Data #10

### PR DESCRIPTION
**Pull request by sdiby**
@ptatian ready for your review

### CODE REVIEW

**Comment by sdiby** [comment]
@ptatian this pull request is ready for your review

**Comment by ptatian** [comment]
Thanks, @sdiby. I'm reviewing now. But, is there a difference between the **BPK_Metrics.sas** and **BPKPresentationResults.sas** programs? They seem to be doing the same thing.

**Comment by ptatian** [comment]
@sdiby Sorry, I meant **BridgePk_Tabs.sas**, not **BPK_Metrics.sas**.

**Comment by ptatian** [comment]
Hi @sdiby. Did you have a chance to look at my question?

**Comment by sdiby** [comment]
@ptatian Apologies--there is no difference between BridgePk_Tabs and BPKPresentationResults. I had renamed the latter but ran into some conflicts when I did the pull request. I restored it, but it looks like the folder retained both files. I've removed BridgePk_Tabs for consistency.

**Review by ptatian — APPROVED** [review]
Hi @sdiby. I made a few more changes to correct a variable naming error. Also the output data set on the data step and input data set for proc export were not the same. 

I also changed the location of the CSV files so that it matches wherever you are batch submitting from. That is, if you batch submit the program on D:, the CSV files will be saved to D:. If you batch submit from L:, they will be saved to L:. This is better for testing/reviewing purposes. 

You can go ahead and merge the pull request, sync the changes, and then do a final batch submit on L:. I'm assuming you will need to update the tables that you emailed me earlier after that. 

Please let me know if you have any questions. Thanks!

**Comment by sdiby** [comment]
Thanks @ptatian I'll take a look this afternoon and merge the pull request.

**Comment by sdiby** [comment]
@ptatian , I noticed that you set the non-transposed dataset as the output csv. Is this your preferred output format? Just checking, as the tables I sent you are configured for the transposed variables.

**Comment by ptatian** [comment]
@sdiby Oh, my bad! I didn't see that there was a separate transpose step. Please restore to using the transposed file for creating the CSV. But, unless there's some reason they need to be permanent, I would prefer that **compile_bpk_tabs_&geosuf** and **bpk_tabs_&geosuf** be temporary data sets.

**Comment by sdiby** [comment]
@ptatian no worries! I've made them temporary datasets and changed the csv source back to the transpose file. I'll batch submit and merge now. 

Thank you!

**Pull request merged**
